graph TD
  User["User: zjma12"]
  C_czshi_kxdigit_com["czshi@kxdigit.com"]
  User ---|106| C_czshi_kxdigit_com
  C_zjma12_kxdigit_com["zjma12@kxdigit.com"]
  User ---|60| C_zjma12_kxdigit_com
  C_sczhang24_kxdigit_com["sczhang24@kxdigit.com"]
  User ---|15| C_sczhang24_kxdigit_com
  C_haoren2_kxdigit_com["haoren2@kxdigit.com"]
  User ---|14| C_haoren2_kxdigit_com
  C_pfli12_kxdigit_com["pfli12@kxdigit.com"]
  User ---|14| C_pfli12_kxdigit_com
  C_chaowei2_kxdigit_com["chaowei2@kxdigit.com"]
  User ---|13| C_chaowei2_kxdigit_com
  C_yuhuang18_kxdigit_com["yuhuang18@kxdigit.com"]
  User ---|11| C_yuhuang18_kxdigit_com
  C_pingdai2_kxdigit_com["pingdai2@kxdigit.com"]
  User ---|10| C_pingdai2_kxdigit_com
  D_kxdigit_com["kxdigit.com"]
  User --> D_kxdigit_com
  D_iflytek_com["iflytek.com"]
  User --> D_iflytek_com
  D_vip_baiwang_com["vip.baiwang.com"]
  User --> D_vip_baiwang_com
