graph LR
  Mailbox["Mailbox"]
  D_kxdigit_com["kxdigit.com"]
  Mailbox -->|428| D_kxdigit_com
  D_iflytek_com["iflytek.com"]
  Mailbox -->|41| D_iflytek_com
  D_vip_baiwang_com["vip.baiwang.com"]
  Mailbox -->|2| D_vip_baiwang_com
